-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 29, 2021 at 01:41 PM
-- Server version: 10.4.13-MariaDB
-- PHP Version: 7.2.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `rr_foods`
--

-- --------------------------------------------------------

--
-- Table structure for table `contact_us`
--

CREATE TABLE `contact_us` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone_no` varchar(100) NOT NULL,
  `massage` varchar(100) NOT NULL,
  `submited_at` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `contact_us`
--

INSERT INTO `contact_us` (`id`, `name`, `email`, `phone_no`, `massage`, `submited_at`) VALUES
(1, 'Gaurav Borse', 'gborse108@gmail.com', '9284748275', 'Hello Admin, I wanted to talk with you.', '2021-01-17');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `image` varchar(250) NOT NULL,
  `title` varchar(250) NOT NULL,
  `description` varchar(250) NOT NULL,
  `category` varchar(250) NOT NULL,
  `active` text NOT NULL,
  `grade` text NOT NULL,
  `size` text NOT NULL,
  `colour` text NOT NULL,
  `place_of_origin` text NOT NULL,
  `processing_method` text NOT NULL,
  `packaging` varchar(60) NOT NULL,
  `MOISTURE_CONTENT` varchar(100) NOT NULL,
  `HOT_WATER_INSOLUBLE` varchar(100) NOT NULL,
  `ASH_CONTENT` varchar(100) NOT NULL,
  `ACID_INSOLUBLE_ASH` varchar(100) NOT NULL,
  `MAJOR_DEFECTS` varchar(100) NOT NULL,
  `FOREIGN_MATTER` varchar(100) NOT NULL,
  `T_P_C` varchar(100) NOT NULL,
  `COLIFORMS` varchar(100) NOT NULL,
  `E_COLI` varchar(100) NOT NULL,
  `MOLDS_YEASTS` varchar(100) NOT NULL,
  `STAPH_AUREUS` varchar(100) NOT NULL,
  `B_CEREUS` varchar(100) NOT NULL,
  `SALMONELLA` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `image`, `title`, `description`, `category`, `active`, `grade`, `size`, `colour`, `place_of_origin`, `processing_method`, `packaging`, `MOISTURE_CONTENT`, `HOT_WATER_INSOLUBLE`, `ASH_CONTENT`, `ACID_INSOLUBLE_ASH`, `MAJOR_DEFECTS`, `FOREIGN_MATTER`, `T_P_C`, `COLIFORMS`, `E_COLI`, `MOLDS_YEASTS`, `STAPH_AUREUS`, `B_CEREUS`, `SALMONELLA`) VALUES
(1, 'Dehydrated_White_Onion_Flakes.jpg', 'Dehydrated White Onion Flakes', 'Our dehydrated white onion flakes are white to off-white in colour and free from all kinds of additives or foreign matter. It is used in various mouth-watering food preparations such as sauces, salads, stuffing mixes, casserole mixes, dry soups, meat', 'DehydratedPro', 'Publish', 'A', '8-15 mm', 'White to off-white', 'Maharashtra, India', 'Mature, fresh white onions are washed, trimmed, cut, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 14 kg', '7% max', '20% max', '4% max', '0.5% max', '1 % max', 'NIL', '<300,000/GM', '<1000/GM', '<10/GM', '<1000/GM', '<100/GM', '<100/GM', 'NIL/25 GM'),
(2, 'Dehydrated_White_Onion_Chopped.jpg', 'Dehydrated White Onion Chopped', 'Our dehydrated white onion pieces are white to off-white in colour and free from all kinds of additives or foreign matter. It is used in various mouth-watering food preparations such as sauces, salads, canned/frozen/dried mixes, casserole mixes, dry ', 'DehydratedPro', 'Publish', 'A', '3-5 mm', 'White', 'Maharashtra, India', 'Mature, fresh white onions are washed, trimmed, cut, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '100', '20% max', '4% max', '0.5% max', '1 % max', 'NIL', '<300,000/GM', '<1000/GM', '<10/GM', '<1000/GM', '<100/GM', '<100/GM', 'NIL/25 GM'),
(3, 'Dehydrated_White_Onion_Minced.jpg', 'Dehydrated White Onion Minced', 'Our dehydrated white onion minced pieces are white to off-white in colour and free from all kinds of additives or foreign matter. It is used for onion taste well as in  food preparations such as sauces, salads, stuffing mixes, casserole mixes, dry so', 'DehydratedPro', 'Publish', 'A', '1-3 mm', 'White', 'Maharashtra, India', 'Mature, fresh white onions are washed, trimmed, minced, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '7% max', '20% max', '4% max', '0.5% max', '1 % max', 'NIL', '<300,000/GM', '<1000/GM', '<10/GM', '<1000/GM', '<100/GM', '<100/GM', 'NIL/25 GM'),
(4, 'Dehydrated_White_Onion_Granules.jpg', 'Dehydrated White Onion Granules', 'Our dehydrated white onion flakes are white to off-white in colour and free from all kinds of additives or foreign matter. It is used in various mouth-watering food preparations such as sauces, salads, vegetable and meat preparations, cheese, and cra', 'DehydratedPro', 'Publish', 'A & Commercial Grade', '0.5 - 1mm', 'White', 'Maharashtra, India', 'Mature, fresh white onions are washed, cut, grounded and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 14 kg or 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(5, 'Dehydrated_White_Onion_Powder.jpg', 'Dehydrated White Onion Powder', 'Onion powder is a popular seasoning made from dehydrated ground onions. This potent-smelling spice is commonly used in dry rubs or marinades to acquire a concentrated onion flavour without the moisture and maintaining bulk of the onion bulb itself. T', 'DehydratedPro', 'Publish', 'A & Commercial Grade', '100 Mesh', 'White', 'Maharashtra, India', 'Mature, fresh white onions are washed, trimmed, cut, grinded, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(6, 'Dehydrated_Pink_Onion_Flakes.png', 'Dehydrated Pink Onion Flakes', 'Our dehydrated pink onion flakes are free from all kinds of additives or foreign matter. It has the same aroma, flavour and taste as freshly cut onions. Commonly used in varied food and salad preparations wherever along with onion flavor & taste, whe', 'DehydratedPro', 'Publish', 'A, B & Commercial Grade', '10 to 25 mm', 'Pink', 'Maharashtra, India', 'Mature, fresh pink onions are washed, trimmed, cut, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 14 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(7, 'Dehydrated_Pink_Onion_Chopped.jpg', 'Dehydrated Pink Onion Chopped', 'Our dehydrated pink onion chopped pieces are free from all kinds of additives or foreign matter. It is used in various mouth-watering food preparations such as sauces, salads, stuffing mixes, casserole mixes, dry soups, meat preparations and fast foo', 'SprayDriedPro', 'Publish', 'A, B & Commercial Grade', '5 to 8 mm', 'Pink', 'Maharashtra, India', 'Mature, fresh pink onions are washed, trimmed, chopped, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(8, 'Dehydrated_Pink_Onion_Minced.jpg', 'Dehydrated Pink Onion Minced', 'Our dehydrated pink onion minced pieces are free from all kinds of additives or foreign matter. It is used in preparation of soups, sauces, canned/dried/frozen foods, salad dressings, meat products and other food products whenever onion flavor or tas', 'SprayDriedPro', 'Publish', 'A, B & Commercial Grade', '1-3 mm', 'Pink', 'Maharashtra, India', 'Mature, fresh pink onions are washed, trimmed, cut, minced, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(9, 'Dehydrated_Pink_Onion_Granules.png', 'Dehydrated Pink Onion Granules', 'Our dehydrated pink onion granules are free from all kinds of additives or foreign matter. It is used in various mouth-watering food preparations such as Vegetables & Meat preparations, gravies, sauces, seasoning, salad dressings, cheese, crackers, a', 'DehydratedPro', 'Publish', 'A', '1-3 mm', 'Pink', 'Maharashtra, India', 'Mature, fresh pink onions are washed, trimmed, cut, granulated, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(10, 'Dehydrated_Pink_Onion_Powder.png', 'Dehydrated Pink Onion Powder', 'Our dehydrated pink onion powder is free from all kinds of additives or foreign matter. The Free-flowing powder is mainly used in soups, sauces, seasoning, meat products and suitable for varied food preparations, especially when a strong onion flavor', 'DehydratedPro', 'Publish', 'A', '100 Mesh to 120 Mesh', 'Pink', 'Maharashtra, India', 'Mature, fresh pink onions are washed, trimmed, cut, grinded, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(11, 'Dehydrated_Red_Onion_Flakes.jpg', 'Dehydrated Red Onion Flakes', 'Our dehydrated healthy red onion flakes are free from all kinds of additives or foreign matter. Its red colour comes from anthocyanins which makes it the healthiest option when used in various delicious food preparations such as sauces, salads, stuff', 'SprayDriedPro', 'Publish', 'A, B & Commercial Grade', '8-15 mm', 'Red', 'Maharashtra, India', 'Mature, fresh red onions are washed, trimmed, cut, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 14 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(12, 'Dehydrated_Red_Onion_Chopped.jpg', 'Dehydrated Red Onion Chopped', 'Our dehydrated healthy red onion chopped pieces are free from all kinds of additives or foreign matter. Its red colour comes from anthocyanins which makes it the healthiest option among the onion family and is used in various mouth-watering food prep', 'SprayDriedPro', 'Publish', 'A, B & Commercial Grade', '5-8 mm', 'Red', 'Maharashtra, India', ': Mature, fresh red onions are washed, trimmed, cut, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 14 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(13, 'Dehydrated_Red_Onion_Minced.png', 'Dehydrated Red Onion Minced', 'Our dehydrated red onion minced pieces are free from all kinds of additives or foreign matter. It is filled with anthocyanins and used in various mouth-watering food preparations such as sauces, salads, stuffing mixes, casserole mixes, dry soups, mea', 'SprayDriedPro', 'Publish', 'A, B & Commercial Grade', '1-3 mm', 'Red', 'Maharashtra, India', ': Mature, fresh red onions are washed, trimmed, cut, minced, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(14, 'Dehydrated_Red_Onion_Granules.png', 'Dehydrated Red Onion Granules', 'Our healthy dehydrated red onion granules are free from all kinds of additives or foreign matter. It contains anthocyanins and is used in various mouth-watering food preparations such as Vegetables & Meat preparations, gravies, sauces, seasoning, sal', 'DehydratedPro', 'Publish', 'A', '0.5 - 1 mm', 'Red', 'Maharashtra, India', 'Mature, fresh red onions are washed, trimmed, cut, grounded, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(15, 'Dehydrated_Red_Onion_Powder1.png', 'Dehydrated Red Onion Powder', 'Our dehydrated red onion powder is filled with anthocyanins which give its natural red colour and is free from all kinds of additives or foreign matter. The Free-flowing grounded powder is mainly used in soups, sauces, seasoning, meat products and su', 'DehydratedPro', 'Publish', 'A', '80 - 100 Mesh', 'Red to off-red', 'Maharashtra, India', 'Mature, fresh red onions are washed, trimmed, cut, and grinded, dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(16, 'Dehydrated_Garlic_Flakes.png', 'Dehydrated Garlic Flakes', 'Our dehydrated garlic cloves and flakes are free from all kinds of additives or foreign matter. It is applied in various mouth-watering food preparations such as salads, burgers, pizzas, canned soups & fast-food.  It’s extremely healthy benefits make', 'SprayDriedPro', 'Publish', 'A, B & Commercial Grade', '8-14 mm', 'Off-White to Creamy White', 'Maharashtra, India', 'Mature, fresh white garlic cloves are washed and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 14 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(17, 'Dehydrated_Garlic_Chopped.jpg', 'Dehydrated Garlic Chopped', 'Our dehydrated garlic chopped pieces are free from all kinds of additives or foreign matter. This form is widely used in varied food preparations whenever strong garlic flavor & taste are desired. It is also utilized for pickles, sauces, canned/prepa', 'DehydratedPro', 'Publish', 'A & Commercial Grade', '5-8 mm', 'Off-White to Creamy White', 'Maharashtra, India', 'Mature, fresh white garlic cloves are washed, trimmed, chopped and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 14 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(18, 'Dehydrated_Garlic_Minced.png', 'Dehydrated Garlic Minced', 'Our dehydrated minced garlic pieces are free from all kinds of additives or foreign matter. Widely used for bottled packs in retail stores for sauces, salad dressings, canned & prepared foods, meat balls, dry casserole mixes. It’s health benefits are', 'SprayDriedPro', 'Publish', 'A, B & Commercial Grade', '1-8 mm', 'Off-White to Creamy White', 'Maharashtra, India', 'Mature, fresh white garlic cloves are washed, trimmed, minced, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 14 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(19, 'Dehydrated_Garlic_Granules.jpg', 'Dehydrated Garlic Granules', 'A dried form of garlic that has been ground into granules rather than powder. Granulated garlic has about half the flavoring power as the same measure of garlic powder and minimize the garlic texture of a fresh clove. Popularly used in salad dressing', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '0.3 - 1.0mm', 'Off-White to Creamy White', 'Maharashtra, India', 'Mature, fresh white garlic cloves are washed, trimmed, grounded, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 14 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(20, 'Dehydrated_Garlic_Powder.jpg', 'Dehydrated Garlic Powder', 'A dried form of garlic that has been ground into fine particles. Granulated garlic has about half the flavoring power as the same measure of garlic powder and minimize the garlic texture of a fresh clove. Popularly applied in soups, sauces, seasoning', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '100-200 meshes', 'Off-White to Creamy White', 'Maharashtra, India', 'Mature, fresh white garlic cloves are washed, trimmed, grounded, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 14 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(21, 'Dehydrated_Ginger_Flakes.jpg', 'Dehydrated Ginger Flakes', 'Our dehydrated ginger flakes are free of additives or foreign matter. Prepared by drying fresh ginger at our state-of-the-art manufacturing unit, these are widely used as a flavoring agent in various food items like pizza, curry, soup, fast foods, an', 'DehydratedPro', 'Publish', 'A', '8-14 mm', 'Yellowish-brown', 'Maharashtra, India', 'Mature, ginger pieces are washed, trimmed, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(22, 'Dehydrated_Ginger_Powder.jpg', 'Dehydrated Ginger Powder', 'Our dehydrated ginger powders are processed at our modern processing unit and the powder is free of additives or foreign matter. The grounded free flowing powder has a long life filled with high nutrition and is used as a flavoring agent in various f', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '8-14 mm', 'Creamy dark yellow', 'Maharashtra, India', 'Mature, ginger pieces are washed, trimmed, grounded, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(23, 'Dehydrated_Potato_Flakes.png', 'Dehydrated Potato Flakes', 'Dehydrated Potato flakes are made from all-natural dehydrated potatoes. The potatoes are cooked, mashed, and dehydrated to yield a packaged convenience food. Dehydrated potato flakes are considered a great alternative to other starches as thickening ', 'DehydratedPro', 'Publish', 'A', '8-14 mm', 'Whitish yellow', 'Maharashtra, India', 'Mature, potato pieces are washed, peeled, trimmed, cut and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(24, 'Dehydrated_Potato_Powder.jpg', 'Dehydrated Potato Powder', 'Dehydrated Potato free-flowing powder is made from all-natural dehydrated grinded potatoes without any additives or foreign matter. Potatoes are dehydrated under a constant stream of warm air, until the moisture content is less to manufacture dehydra', 'DehydratedPro', 'Publish', 'A', '80 - 120 Mesh', 'Whitish yellow', 'Maharashtra, India', 'Mature, potato pieces are washed, peeled, sliced, bleached, grinded, and dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 25 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(25, 'Dehydrated_Green_Chilli_Flakes.png', 'Dehydrated Green Chilli Flakes', 'Dehydrated green chilli flakes are free from foreign impurities which are used in ready to eat products. It finds its use in adding natural flavor & color to the prepared dishes, it has extensive use in Thai, Mexican and Indian cuisine preparation du', 'DehydratedPro', 'Publish', 'A & Commercial Grade', '1-5 mm', 'Green', 'Maharashtra, India', 'Mature green chilli pieces are washed, sliced, grinded, and then dehydrated by passing through a Hot air Closed Continuous System. ', 'Bag of 14 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(26, 'Dehydrated_Green_Chilli_Powder.png', 'Dehydrated Green Chilli Powder', 'Green Chilli Powder is made from 100% natural Green Chilli, through best dehydration technology which is free from foreign impurities and free flowing. It finds its use in adding natural flavor & color to the prepared dishes, it has extensive use in ', 'DehydratedPro', 'Publish', 'A & Commercial Grade', '80 - 120 Mesh', 'Green', 'Maharashtra, India', 'Mature green chilli pieces are washed, sliced, grinded, and then dehydrated by passing through a Hot air Closed Continuous System. ', 'Bag of 25 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(27, 'Dehydrated_Carrot_Cubes.png', 'Dehydrated Carrot Cubes', 'Dehydrated carrot stands out for its rich taste, which infuses with the overall flavour of the dish that it is used in. The sweetness of the cubes or flakes is completely natural, healthy and there are no added artificial flavour and preservatives. B', 'DehydratedPro', 'Publish', 'A', '1-5 mm', 'Reddish Orange', 'Maharashtra, India', 'Mature carrots are washed, peeled, chopped, and then dehydrated by passing through a Hot air Closed Continuous System. ', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(28, 'Dehydrated_Carrot_Powder.png', 'Dehydrated Carrot Powder', 'Dehydrated carrot powder stands out for its free flow, rich taste, which infuses with the overall flavour of the dish that it is used in. The sweetness of the powder is completely natural, healthy and there are no added artificial flavour, colours an', 'DehydratedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Light Orange', 'Maharashtra, India', 'Mature carrots are washed, peeled, chopped, grinded and then dehydrated by passing through a Hot air Closed Continuous System. ', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(29, 'Dehydrated_Tomato_Flakes.png', 'Dehydrated Tomato Flakes', 'Dehydrated Tomato Flakes are free of additives and are finely chopped and dehydrated at our modern infrastructural facility. These dried tomato flakes add vibrant color and impressive depth of flavor to all sorts of dishes and we especially love to u', 'DehydratedPro', 'Publish', 'A', '8-10 mm', 'Red', 'Maharashtra, India', 'Mature tomatoes are washed, sliced, and then dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(30, 'Dehydrated_Beet_Root_powder.png', 'Dehydrated Beet Root powder', 'Dehydrated Beet root powder is free of additives and has free flow. Once sliced beets are thoroughly dehydrated, then it is finely ground to make a powder. The powder after a rigorous process is then ready for packaging. Dehydrated beet root powder i', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Dark Reddish Pink', 'Maharashtra, India', 'Mature beets are washed, sliced, grounded, and then dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(31, 'Dehydrated_Fenugreek_Leaves.png', 'Dehydrated Fenugreek Leaves', 'Fenugreek is used both as an herb (the leaves) and as a spice. During the air drying and packaging procedure, we keep the hygienic level high and also ensure that there is no human touch. Appreciated for its amazing smell and fine taste, the Dehydrat', 'DehydratedPro', 'Publish', 'A & Commercial Grade', '20-25 mm', 'Green', 'Maharashtra, India', 'Fenugreek Leaves are washed, cleaned, air-dried, and then dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(32, 'Dehydrated_Curry_Leaves.png', 'Dehydrated Curry Leaves', 'All the raw materials used to manufacture this product are NON-GMO in origin. During the air drying and packaging procedure, we keep the hygienic level high and also ensure that there is no human touch. Appreciated for its amazing smell and fine tast', 'DehydratedPro', 'Publish', 'A & Commercial Grade', '20-80 mm', 'Green', 'Maharashtra, India', 'Curry Leaves are washed, sorted, cleaned, air-dried, and then dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(33, 'Dehydrated_Mint_Leaves.png', 'Dehydrated Mint Leaves', 'Mint Leaves are quite popular for their varied unique properties. They can be preserved and stored for a longer period of time while retaining their original aroma or fragrance. Mint Leaves are widely used for making different medicines and medicinal', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '4-10 mm', 'Green with tinges of brown', 'Maharashtra, India', 'Mint Leaves are washed, sorted, cleaned, air-dried, and then dehydrated by passing through a Hot air Closed Continuous System.', 'Bag of 15 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(34, 'Dehydrated_Mint_Powder.png', 'Dehydrated Mint Powder', 'Our Dehydrated free flowing Mint Powder is prepared by grinding dried mint leaves under the observation of experts to ensure no foreign matter or additives are present. During the air drying and packaging procedure, we keep the hygienic level high an', 'DehydratedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Green', 'Maharashtra, India', 'Mint Leaves are washed, sorted, cleaned, air-dried, grounded, and then dehydrated by passing through a Hot air Closed Continuous System. ', 'Bag of 20 kg', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(35, 'Fried_Onion.jpg', 'Fried Onion', 'We prepare fried onion from red and white onions without using any additives. Under hygienic conditions we carefully auto-controlled continuous frying helps fry onion flakes with high quality edible oil so that the texture, taste, crispiness, and aro', 'DehydratedPro', 'Publish', 'A, B & Commercial Grade', '8-20 mm', 'Golden brown', 'Maharashtra, India', 'Mature onion pieces are peeled, washed, trimmed, and dehydrated by passing through a Hot air Closed Continuous System.', '285-500 gms/Ltr', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(36, 'Tomato_Powder.png', 'Tomato Powder', 'Extremely fresh and pure, our 100% natural spray dried Tomato Powder has no traces of any dust, pollutants, or impurities. The tangy taste and mild aroma adds great flavor to any culinary item. Tomato Powder is one of the most widely used ingredients', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Red', 'Maharashtra, India', 'We have a fully integrated manufacturing plant through which we handle fresh tomatoes which are processed into Tomato Pulp. Through our in-house Concentration facility, we concentrate the Tomato Pulp in Tomato Paste to later Spray Dry it.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(37, 'Lemon_Powder.png', 'Lemon Powder', 'Extremely fresh and pure, our 100% natural spray dried Lemon Powder has no traces of any dust, pollutants, or impurities. The natural colour, fresh taste coupled with a mild aroma adds great flavor to any beverages, confectionery, and culinary item. ', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Yellow', 'Maharashtra, India', 'Fresh lemons are passed through a washing vat for the cleaning and sorting. The bad lemon fruits are separated whereas the skin and seeds are carefully removed, and final juice is then filtered. The lemon juice is then concentrated with the help of evaporators. The concentrated juice is spray dried to get Lemon fruit powder. The powder is finally sieved through a vibratory sleeve to result in the fine free flowing natural lemon powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(38, 'Strawberry_Powder.png', 'Strawberry Powder', 'Extremely fresh and pure, our 100% natural spray dried Strawberry Powder has no traces of any dust, pollutants, or impurities. The natural colour, fresh taste coupled with a mild aroma adds great sweet and tangy flavor to any beverages, confectionery', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Pinkish Red', 'Maharashtra, India', 'Fresh strawberries are passed through a washing vat for the cleaning and sorting. The bad strawberry fruits are separated whereas the skin and seeds are carefully removed, and final juice is then filtered. The strawberry juice is then concentrated with the help of evaporators. The concentrated juice is spray dried to get Strawberry fruit powder. The powder is finally sieved through a vibratory sleeve to result in the fine free flowing natural strawberry powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(39, 'Banana_Powder.png', 'Banana Powder', 'Extremely fresh and pure, our 100% natural spray dried Banana Powder has no traces of any dust, pollutants, or impurities. The natural colour, fresh taste coupled with a mild aroma adds great sweet and tangy flavor to any beverages, confectionery, de', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Creamy Yellow', 'Maharashtra, India', 'Fresh bananas are passed through a washing vat for the cleaning and sorting. The skin is carefully removed and passes through milling to form past. The paste is then dried by either spray or drum drying, then the powder is sieved through a vibratory sleeve to result in the fine free flowing natural banana powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(40, 'Carrot_Powder.png', 'Carrot Powder', 'Extremely fresh and pure, our 100% natural spray dried Banana Powder has no traces of any dust, pollutants, or impurities. The natural colour, fresh taste coupled with an invigorating aroma adds mild sweet flavor to any beverages, confectionery, dess', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Orange', 'Maharashtra, India', 'Fresh carrots are harvested, washed, pulped, screened, and concentrated into carrot juice concentrate. The concentrate is then dried through an innovative low temperature process. The powder is then milled and packaged under a nitrogen atmosphere.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(41, 'Lychee_Powder.png', 'Lychee Powder', 'Extremely fresh and pure, our 100% natural spray dried Lychee Powder has no traces of any dust, pollutants, or impurities. The natural colour, fresh taste coupled with a mild aroma add sweetness and softness of Lychees to any beverages, confectionery', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Off-White', 'Maharashtra, India', 'Fresh lychees are harvested, washed, pulped, screened, and concentrated into lychee juice concentrate. The concentrate is then dried through an innovative low temperature process. The powder is then milled and packaged under a nitrogen atmosphere to maintain freshness.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(42, 'Beetroot_Powder.png', 'Beetroot Powder', 'Extremely fresh and pure, our 100% natural spray dried Beetroot Powder has no traces of any dust, pollutants, or impurities. The natural colour, fresh taste coupled with a mild aroma adds real flavour of Beets to any beverages, confectionery, dessert', 'SprayDriedPro', 'Publish', 'A', '80 Mesh', 'Dark Red', 'Maharashtra, India', 'Fresh beetroots are harvested, washed, peeled, pulped, screened, and concentrated into beetroot juice concentrate. The concentrate is then dried through an innovative low-temperature process. The powder is then milled and packaged under a nitrogen atmosphere to maintain freshness.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(43, 'Mango_Powder.png', 'Mango Powder', 'Extremely fresh and pure, our 100% natural spray dried Mango Powder has no traces of any dust, pollutants, or impurities. The natural yellow colour, fresh sweet taste coupled with a strong aroma adds real flavour of Mangoes to any beverages, confecti', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Creamy Yellow and slight Tan', 'Maharashtra, India', 'Fresh mangoes are harvested, washed, peeled, pulped, screened, and concentrated into mango juice concentrate. The concentrate is then dried through an innovative low temperature process. The powder is then milled and packaged under a nitrogen atmosphere to maintain freshness.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(44, 'Pomegranate_Powder.png', 'Pomegranate Powder', 'Extremely fresh and pure, our 100% natural spray dried Pomegranate Powder has no traces of any dust, pollutants, or impurities. The natural free flowing pinkish colour, fresh sweet and mildly sour taste coupled with a strong aroma adds real flavour o', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Light Pink', 'Maharashtra, India', 'Fresh pomegranates are passed through washing vat for the cleaning and sorting. After removing the bad fruits aside, the skin is carefully removed and pomegranate juice is filtered. Further the pomegranate juice is concentrated with the help of evaporators. Carrier is added to the concentrated juice which is spray dried to get Pomegranate fruit powder. Then the powder is sieved through a vibratory sleeve to result in the fine free flowing natural pomegranate powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(45, 'Guava_Powder.png', 'Guava Powder', 'Extremely fresh and pure, our 100% natural spray dried Guava Powder has no traces of any dust, pollutants, or impurities. The free flowing natural pinkish colour, fresh unique taste coupled with a strong aroma adds real flavour of Guavas to any bever', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Light Pink', 'Maharashtra, India', 'Fresh guavas are passed through washing vat for the cleaning and sorting out bad guavas. The skin and seeds are carefully removed, and guava juice is then filtered. The guava juice is then concentrated with the help of evaporators. Carrier is added to the concentrated juice then the juice is spray dried to get Guava fruit powder. Then the powder is sieved through a vibratory sleeve to result in the fine free flowing natural guava powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(46, 'Pineapple_Powder.png', 'Pineapple Powder', 'Extremely fresh and pure, our 100% natural spray dried Pineapple Powder has no traces of any dust, pollutants, or impurities. The free flowing natural yellow colour, fresh sweet taste coupled with a strong aroma adds real flavour of Pineapples to any', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Light Yellow', 'Maharashtra, India', 'Fresh Pineapples are passed through washing vat for the cleaning and sorting of bad fruits is done. The skin is carefully removed, and pineapple juice is then filtered. Then the juice is concentrated with the help of evaporators. The concentrated pulp is spray dried to get Pineapple fruit powder. Then the powder is sieved through a vibratory sleeve to result in the fine free flowing natural pineapple powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(47, 'Orange_Powder.png', 'Orange Powder', 'Extremely fresh and pure, our 100% natural spray dried Orange Powder has no traces of any dust, pollutants, or impurities. The free-flowing natural light orange colour, fresh and tangy sweet taste coupled with a strong aroma adds real flavour of Oran', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Orange', 'Maharashtra, India', 'Fresh oranges are passed through washing vat for the cleaning and sorting. The bad orange fruits are separated and further broken. The skin and seeds are carefully peeled and removed, from which juice is then filtered. The Orange juice is then concentrated with the help of evaporators. The concentrated juice is spray dried to get Orange fruit powder. Finally, the powder is sieved through a vibratory sleeve to result in the fine free flowing natural orange powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(48, 'Papaya_Powder.png', 'Papaya Powder', 'Extremely fresh and pure, our 100% natural spray dried Papaya Powder has no traces of any dust, pollutants, or impurities. The free-flowing natural light orange colour, pungent taste coupled with a strong aroma adds real flavour of papayas to any cul', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Light Yellow', 'Maharashtra, India', 'Fresh papayas are passed through washing vat for cleaning of fruits after and sorting. The bad Papaya fruits are separated and further broken. The skin and seeds are carefully removed, and papaya juice is then filtered. Furthermore, the papaya juice is concentrated with the help of evaporators. Carrier is added to the concentrated juice and then the juice is spray dried to get papaya fruit powder. Finally, the powder is sieved through a vibratory sleeve to result in the fine free flowing natural papaya powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(49, 'Mint_Powder.png', 'Mint Powder', 'Extremely fresh and pure, our 100% natural spray dried Mint Powder has no traces of any dust, pollutants, or impurities. The free-flowing natural green colour, cool menthol taste coupled with a strong aroma adds real flavour of mint. Dry Mint Powder ', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Green', 'Maharashtra, India', 'To remove the impurity mint slurry is passed through basket filter. The mint slurry is then passed through clarification to remove impurities. The slurry is then concentrated using evaporator. Carrier is added to the concentrated slurry then the slurry is spray dried to get Mint Powder. Then the powder is sieved through a vibratory sleeve to result in the fine free flowing natural mint powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(50, 'Cream_Powder1.png', 'Cream Powder', 'This cream powder is manufactured from pasteurised fresh cream and has undergone spray drying which has no traces of any dust, pollutants, or impurities. The free-flowing natural milk colour, milky and creamy taste which is odorless adds real flavour', 'DehydratedPro', 'Publish', 'A', '80 Mesh', 'Creamy Off-White', 'Maharashtra, India', 'Spray drying, also called drying by atomization, is a particle drying technique. It consists in spraying the product to be dried, in liquid form or suspended, in a warm gas flow in order to obtain a powder. Spray drying is also a drag-out drying technique. Whenever a humid body is placed in a dry and warm air flow (or another gas), a gap of temperature and partial pressure spontaneously happens so that a warmth transfer occurs from the air to the product under the influence of the temperature gap, between the air and the product surface. Air acts both as heating fluid and as a carrier gas to drag out water. Gas goes in the drying tower warm and dry, then comes out of it humid and cooled resulting in free-flowing cream powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(51, 'Cheese_Powder.png', 'Cheese Powder', 'Our 100% natural spray dried cheese powders are made from natural, vegetarian, and premium cheese that is sourced from only reputed dairies in India, which has no traces of any dust, pollutants, or impurities. The free-flowing yellow colour, cheesy t', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Yellow', 'Maharashtra, India', 'In order to spray dry cheese, it is necessary to bring it into a liquid form. This is done by a normal melting process where the cheese rind, if any, is removed, the cheese is disintegrated, and during heating and agitation melting salts such as phosphates and citrates are added together with water. With the help of evaporators, a carrier is added to the concentrated liquid which is spray dried to get cheese powder. Finally, the powder is sieved through a vibratory sleeve to result in the fine free flowing natural cheese powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(52, 'Dates_Powder.png', 'Dates Powder', 'Extremely fresh and pure, our 100% natural Dates Powder has no traces of any dust, pollutants, or impurities. The free-flowing natural brown colour, sweet taste coupled with a strong aroma adds real flavour of dates. Dates are particularly good sourc', 'DehydratedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Brown', 'Maharashtra, India', 'Fresh dates are passed through a washing vat for the cleaning and sorting. The bad date fruits are separated whereas the skin and seeds are carefully removed, and final juice is then filtered. The date pulp is then liquefied and concentrated with the help of evaporators. Spray Dried Dates Powder is created out of the juice extracted out of the Dates fruit that is generally concentrated and pasteurised to be later mixed with a carrier so as to ensure uniform drying. The mixture is then fed into a spray dryer and pumped through a tiny nozzle into a heated chamber with a blow of hot air that causes quick evaporation of water from the mixture resulting in the fruit powder to get collected at the outlet.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(53, 'Honey_Powder.png', 'Honey Powder', 'Extremely fresh and pure, our 100% natural Honey Powder has no traces of any dust, pollutants, or impurities. The free-flowing natural dark golden colour, sweet taste coupled with a strong aroma adds real flavour of honey. Apart from its medicinal be', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Light Golden-Brown', 'Maharashtra, India', 'Pure Honey is blended along with fresh water in a calculated ratio to create a less viscosity-based (for avoiding clogging) liquid. To remove the impurity the liquid is passed through basket filter. The liquid is then concentrated using evaporator. Carrier is added to the concentrated liquid and is then spray dried to get honey Powder. Then the powder is sieved through a vibratory sleeve to result in the fine free flowing natural honey powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(54, 'Caramel_Powder.png', 'Caramel Powder', 'Extremely fresh and pure, our 100% natural caramel Powder has no traces of any dust, pollutants, or impurities. The free-flowing natural light brown colour, sweet taste coupled with a pleasant aroma adds real flavour of caramel. Caramel, sometimes ca', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Brown', 'Maharashtra, India', 'Molasses are heated at high temperatures and then blended along with little fresh water in a calculated ratio to create a less viscosity-based (for avoiding clogging) caramel liquid. To remove the impurity the liquid is passed through basket filter. The liquid is then concentrated using evaporator. Carrier is added to the concentrated liquid and is then spray dried to get caramel Powder. Then the powder is sieved through a vibratory sleeve to result in the fine free flowing natural caramel powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(55, 'Green_Chilli_Powder.png', 'Green Chilli Powder', 'Extremely fresh and pure, our 100% natural green chilli Powder has no traces of any dust, pollutants, or impurities. The free-flowing natural green colour, spicy taste coupled with a pleasant aroma adds real flavour of green chillies. It finds its us', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Green', 'Maharashtra, India', 'To remove impurities green chili slurry is passed through a basket filter. The slurry is then passed through clarification to remove impurities. The green chili slurry is then concentrated using evaporator. Carrier is added to the concentrated slurry then the slurry is spray dried to get Green chili Powder. Then this powder is sieved through a vibratory sleeve to result in fine free flowing natural green chili powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(56, 'Coriander_Leaves_Powder.png', 'Coriander Leaves Powder', 'Extremely fresh and pure, our 100% natural coriander Powder has no traces of any dust, pollutants, or impurities. The free-flowing natural green colour, mildly spicy, earthy and nutty taste coupled with a pleasant aroma adds real flavour of coriander', 'SprayDriedPro', 'Publish', 'A & Commercial Grade', '80 Mesh', 'Green', 'Maharashtra, India', 'Coriander leaves are washed and then passed through a filter basket clarification to remove impurities. The slurry of coriander leaves is then concentrated using evaporator. Carrier is added to the concentrated slurry then the slurry is spray dried to get coriander Powder. Then this powder is sieved through a vibratory sleeve to result in fine free flowing natural coriander powder.', 'As per clients requirements', '', '', '', '', '', '', '', '', '', '', '', '', '');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` varchar(30) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `active` text NOT NULL,
  `created_at` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`, `active`, `created_at`) VALUES
(1, 'Gaurav Borse', 'gborse108@gmail.com', 'root', 'Publish', '2021-01-01'),
(2, 'Admin', 'admin@gmail.com', 'admin', 'Publish', '2021-01-11');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `contact_us`
--
ALTER TABLE `contact_us`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `contact_us`
--
ALTER TABLE `contact_us`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=58;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
